# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a72f673251f646f6f71df14c3c531fe62fff6ab17382acc611253f9947053017b60c8fdee0ce1972a821335119858712cbbb3c6aeaf1766969f1b70deb65d1a

test:
  secret_key_base: 5ad4a3d9880be91121343b1d4f9bc96f3f9e4435bd1b68c8051f0c73317b6b618cf0e32852de2b2538697ab2c6ae5964558c80351062d4c06b5b89608f79b26f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
